// version.h — generated by Make from CMakeLists.txt
//  1.4.0  → e.g. 1.4.0
//  16     → git commit count

#ifndef SLAPTRACK_VERSION_H
#define SLAPTRACK_VERSION_H

#define SLAPTRACK_VERSION "1.4.0"
#define SLAPTRACK_BUILD   "16"

#endif // SLAPTRACK_VERSION_H
