// version.h — generated by Make from CMakeLists.txt
//  1.3.1  → e.g. 1.4.0
//  15     → git commit count

#ifndef SLAPTRACK_VERSION_H
#define SLAPTRACK_VERSION_H

#define SLAPTRACK_VERSION "1.3.1"
#define SLAPTRACK_BUILD   "15"

#endif // SLAPTRACK_VERSION_H
